#!/bin/sh

echo "growmat runserver"

#nohup python ./growmat/growmat/manage.py modbus &
#nohup python ./growmat/growmat/manage.py archive &
python ./growmat/manage.py runserver 0.0.0.0:80

#nohup fswebcam -c /etc/fswebcam.conf &
